### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by mcepl** [spyder-ide/spyder-memory-profiler#20] opened 2019-04-23 09:35 UTC
When running the testsuite from version 0.1.2 on openSUSE/Tumbleweed (this time Python 2.7.16) I get it failing ([complete build log](https://github.com/spyder-ide/spyder-memory-profiler/files/3106847/log.txt):
```
[   37s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.NqO9nA
[   37s] + umask 022
[   37s] + cd /home/abuild/rpmbuild/BUILD
[   37s] + cd spyder_memory_profiler-0.1.2
[   37s] + export QT_HASH_SEED=0
[   37s] + QT_HASH_SEED=0
[   37s] + export DISPLAY=:98
[   37s] + DISPLAY=:98
[   37s] + export PYTHONDONTWRITEBYTECODE=1
[   37s] + PYTHONDONTWRITEBYTECODE=1
[   37s] + trap 'kill 18329 || true' EXIT
[   37s] + sleep 10
[   37s] + Xvfb :98
[   48s] ++ '[' -f _current_flavor ']'
[   48s] ++ cat _current_flavor
[   48s] + python_flavor=python3
[   48s] + '[' -z python3 ']'
[   48s] + '[' python3 '!=' python2 ']'
[   48s] + '[' -d build ']'
[   48s] + mv build _build.python3
[   48s] + '[' -d _build.python2 ']'
[   48s] + mv _build.python2 build
[   48s] + echo python2
[   48s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-spyder-memory-profiler-0.1.2-0.x86_64/usr/lib/python2.7/site-packages
[   48s] + py.test-2.7 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v spyder_memory_profiler
[   48s] ============================= test session starts ==============================
[   48s] platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.8.0, pluggy-0.9.0 -- /usr/bin/python2
[   48s] cachedir: .pytest_cache
[   48s] PyQt5 5.12 -- Qt runtime 5.12.2 -- Qt compiled 5.12.2
[   48s] rootdir: /home/abuild/rpmbuild/BUILD/spyder_memory_profiler-0.1.2, inifile:
[   48s] plugins: qt-3.2.2
[   49s] collecting ... collected 1 item
[   49s] 
[   50s] spyder_memory_profiler/widgets/tests/test_memoryprofiler.py::test_profile_and_display_results FAILED [100%]
[   50s] 
[   50s] =================================== FAILURES ===================================
[   50s] _______________________ test_profile_and_display_results _______________________
[   50s] 
[   50s] qtbot = <pytestqt.qtbot.QtBot object at 0x7fcd95fc2b50>
[   50s] tmpdir = local('/tmp/pytest-of-abuild/pytest-0/test_profile_and_display_resul0')
[   50s] monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fcd95fc2f10>
[   50s] 
[   50s]     @pytest.mark.qt_log_level_fail('WARNING')
[   50s]     def test_profile_and_display_results(qtbot, tmpdir, monkeypatch):
[   50s]         """
[   50s]         Run profiler on simple script and check that results are okay.
[   50s]     
[   50s]         This is a fairly simple integration test which checks that the plugin works
[   50s]         on a basic level.
[   50s]         """
[   50s]         os.chdir(tmpdir.strpath)
[   50s]         testfilename = tmpdir.join('test_foo.py').strpath
[   50s]     
[   50s]         with open(testfilename, 'w') as f:
[   50s]             f.write(TEST_SCRIPT)
[   50s]     
[   50s]         MockQMessageBox = Mock()
[   50s]         monkeypatch.setattr('spyder_memory_profiler.widgets.memoryprofiler.QMessageBox',
[   50s]                             MockQMessageBox)
[   50s]     
[   50s]         widget = MemoryProfilerWidget(None)
[   50s]         qtbot.addWidget(widget)
[   50s]         with qtbot.waitSignal(widget.sig_finished, timeout=10000, raising=True):
[   50s]             widget.analyze(testfilename)
[   50s]     
[   50s]         MockQMessageBox.assert_not_called()
[   50s]         dt = widget.datatree
[   50s]         assert dt.topLevelItemCount() == 1  # number of functions profiled
[   50s]     
[   50s]         top = dt.topLevelItem(0)
[   50s]         assert top.data(0, Qt.DisplayRole).startswith('foo ')
[   50s]         assert top.childCount() == 6
[   50s]         for i in range(6):
[   50s]             assert top.child(i).data(0, Qt.DisplayRole) == i + 1  # line no
[   50s]     
[   50s]         # Column 2 has increment (in MiB); displayed as 'xxx MiB' so need to strip
[   50s]         # last 4 characters. To make the test robust, we only check the sign
[   50s]         assert float(top.child(2).data(2, Qt.DisplayRole)[:-4]) > 0
[   50s]         assert float(top.child(3).data(2, Qt.DisplayRole)[:-4]) > 0
[   50s] >       assert float(top.child(4).data(2, Qt.DisplayRole)[:-4]) < 0
[   50s] E       AssertionError: assert 0.0 < 0
[   50s] E        +  where 0.0 = float('0.000')
[   50s] 
[   50s] /home/abuild/rpmbuild/BUILD/spyder_memory_profiler-0.1.2/spyder_memory_profiler/widgets/tests/test_memoryprofiler.py:78: AssertionError
[   50s] =============================== warnings summary ===============================
[   50s] /usr/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28
[   50s]   /usr/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28: DeprecationWarning: `nbconvert.exporters.exporter_locator` is deprecated in favor of `nbconvert.exporters.base` since nbconvert 5.0.
[   50s]     DeprecationWarning)
[   50s] 
[   50s] -- Docs: https://docs.pytest.org/en/latest/warnings.html
[   50s] ===================== 1 failed, 1 warnings in 2.10 seconds =====================
[   50s] + kill 18329
[   50s] error: Bad exit status from /var/tmp/rpm-tmp.NqO9nA (%check)
```
However, when I exclude the test ``test_profile_and_display_results`` it sitll fails:
```
[   64s] Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.ZK4YpG
[   64s] + umask 022
[   64s] + cd /home/abuild/rpmbuild/BUILD
[   64s] + cd spyder_memory_profiler-0.1.2
[   64s] + export QT_HASH_SEED=0
[   64s] + QT_HASH_SEED=0
[   64s] + export DISPLAY=:98
[   64s] + DISPLAY=:98
[   64s] + export PYTHONDONTWRITEBYTECODE=1
[   64s] + PYTHONDONTWRITEBYTECODE=1
[   64s] + trap 'kill 30885 || true' EXIT
[   64s] + Xvfb :98
[   64s] + sleep 10
[   74s] ++ '[' -f _current_flavor ']'
[   74s] ++ cat _current_flavor
[   74s] + python_flavor=python3
[   74s] + '[' -z python3 ']'
[   74s] + '[' python3 '!=' python2 ']'
[   74s] + '[' -d build ']'
[   74s] + mv build _build.python3
[   74s] + '[' -d _build.python2 ']'
[   74s] + mv _build.python2 build
[   74s] + echo python2
[   74s] + PYTHONPATH=/home/abuild/rpmbuild/BUILDROOT/python-spyder-memory-profiler-0.1.2-0.x86_64/usr/lib/python2.7/site-packages
[   74s] + py.test-2.7 --ignore=_build.python2 --ignore=_build.python3 --ignore=_build.pypy3 -v -k 'not test_profile_and_display_results' spyder_memory_profiler
[   74s] ============================= test session starts ==============================
[   74s] platform linux2 -- Python 2.7.16, pytest-3.10.1, py-1.8.0, pluggy-0.9.0 -- /usr/bin/python2
[   74s] cachedir: .pytest_cache
[   74s] PyQt5 5.12 -- Qt runtime 5.12.2 -- Qt compiled 5.12.2
[   74s] rootdir: /home/abuild/rpmbuild/BUILD/spyder_memory_profiler-0.1.2, inifile:
[   74s] plugins: qt-3.2.2
[   76s] collecting ... collected 1 item / 1 deselected
[   76s] 
[   76s] =============================== warnings summary ===============================
[   76s] /usr/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28
[   76s]   /usr/lib/python2.7/site-packages/nbconvert/exporters/exporter_locator.py:28: DeprecationWarning: `nbconvert.exporters.exporter_locator` is deprecated in favor of `nbconvert.exporters.base` since nbconvert 5.0.
[   76s]     DeprecationWarning)
[   76s] 
[   76s] -- Docs: https://docs.pytest.org/en/latest/warnings.html
[   76s] =================== 1 deselected, 1 warnings in 1.90 seconds ===================
[   76s] + kill 30885
[   76s] error: Bad exit status from /var/tmp/rpm-tmp.ZK4YpG (%check)
```

**Comment by ccordoba12** [comment] 2019-04-23 10:34
@jitseniesen, could you take a look at this? Thanks!

**Comment by jitseniesen** [comment] 2019-04-23 13:44
The failing test seems to be caused by a bug in the memory-profiler package itself: pythonprofilers/memory_profiler#226.

Regarding what happens if you disable the test, I am not sure. It seems that `py.test` runs without errors but that some SUSE-specific code generate an error. Maybe the issue is that `py.test` does not find any tests and thus returns with a [non-zero exit code](https://docs.pytest.org/en/latest/usage.html).

**Comment by mcepl** [comment] 2019-04-23 17:41
Yes, I can confirm that [reverting](https://build.opensuse.org/package/view_file/devel:languages:python/python-memory_profiler/revert-5fe38da92673.patch?expand=1)  https://github.com/pythonprofilers/memory_profiler/commit/5fe38da926738a7715c860053a498859e2db0c87 makes the test suite pass.

**Comment by jitseniesen** [comment] 2023-05-07 11:13
We decided to officially stop maintaining the plugin, so I am closing all issues.

**Closed as not planned by jitseniesen** 2023-05-07 11:13 UTC
Labels: upstream
